sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t davidyagoo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davidyagoo/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-755075019320"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
