sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t davidyagoo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davidyagoo/docker-react npm run test -- --coverage
